[project]
name = "csd-server"
version = "0.1.0"
description = ""
authors = [
    {name = "Jessica Rehak",email = "rehak@lbl.gov"}
]
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
    "flask (>=3.1.2,<4.0.0)",
    "typer (>=0.21.1,<0.22.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
]

[tool.poetry]
packages = [
	{ include = "csd_server", from = "src"}
]


[tool.poetry.scripts]
csd-server = "csd_server.cli:typer_app"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
